### PR TITLE
sendonly: Don't assume we're building on UNIX

### LINKED ISSUE #203: Is Gstwebrtc compatible with Windows
Hi @nirbheek 

Please is Gstwebrtc compatible with Windows?

I am trying to run some of the demos but I keep getting this error message: 

`C:/msys64/mingw64/include/glib-2.0/glib-unix.h:29:10: fatal error: sys/wait.h: No such file or directory`

I am compiling and running it on Msys2 and Mingw toolchain.

thanks.

### PR DESCRIPTION
**Pull request by nirbheek**
Fixes https://github.com/centricular/gstwebrtc-demos/issues/203

### CODE REVIEW

File: sendonly/webrtc-unidirectional-h264.c [hunk 1]
```diff
@@ -531,7 +532,7 @@ get_string_from_json_object (JsonObject * object)
   return text;
 }
 
-
+#ifdef G_OS_UNIX
 gboolean
 exit_sighandler (gpointer user_data)
```
Comment (sdroege) [inline sendonly/webrtc-unidirectional-h264.c:537]: Why is this not `static`?

File: sendonly/webrtc-recvonly-h264.c [hunk 2]
```diff
@@ -649,7 +650,7 @@ get_string_from_json_object (JsonObject * object)
   return text;
 }
 
-
+#ifdef G_OS_UNIX
 gboolean
 exit_sighandler (gpointer user_data)
```
Comment (sdroege) [inline sendonly/webrtc-recvonly-h264.c:655]: Why is this not `static`?

Comment (nirbheek) [reply sendonly/webrtc-recvonly-h264.c:655]: Ah, sorry, didn't see your comments. Just saw that the original reporter confirmed the fix and I hit the button: https://github.com/msys2/MSYS2-packages/issues/2017#issuecomment-647482766
